# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-13 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0035_auto_20210115_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_cancel_meal_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='billing_payment_type',
            field=models.CharField(blank=True, choices=[(' ', '----'), ('3rd', '3rd Party'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('credit', 'Credit card'), ('eft', 'EFT'), ('etransfert', 'e-Transfer')], max_length=10, null=True, verbose_name='Payment Type'),
        ),
        migrations.AddField(
            model_name='client_cancel_meal_date',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_meal_dates', to='member.Client', verbose_name='client'),
        ),
    ]
