# Generated by Django 1.11.29 on 2025-06-08 21:54
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0038_member_verbose_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="billing_payment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (" ", "----"),
                    ("3rd", "3rd Party"),
                    ("credit", "Carte de crédit"),
                    ("cash", "Cash"),
                    ("cheque", "Chèque"),
                    ("creditphon", "Credit téléphone"),
                    ("eft", "EFT"),
                    ("free", "Gratuité"),
                    ("etransfert", "Interac"),
                ],
                max_length=10,
                null=True,
                verbose_name="Payment Type",
            ),
        ),
    ]
