# Generated by Django 1.11.29 on 2025-06-08 21:58
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0039_member_billing_payment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="billing_mailing_type",
            field=models.CharField(
                blank=True,
                choices=[(" ", "----"), ("email", "Email"), ("paper", "Paper")],
                max_length=10,
                null=True,
                verbose_name="Mailing Type",
            ),
        ),
    ]
