# Generated by Django 1.11.29 on 2025-07-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0040_client_billing_mailing_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="billing_email",
            field=models.CharField(
                blank=True, max_length=320, null=True, verbose_name="Billing Email"
            ),
        ),
    ]
