# Generated by Django 1.11.29 on 2025-08-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0041_client_billing_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="country_code",
            field=models.CharField(default="CA", max_length=10, verbose_name="country"),
        ),
        migrations.AddField(
            model_name="address",
            name="region_code",
            field=models.CharField(
                default="QC", max_length=10, verbose_name="province"
            ),
        ),
    ]
